--- # webserver setup
- hosts: appservers
  user: test
  sudo: yes
  tasks:
    - name: installing httpd package
      yum: name=httpd12344  state=installed
      ignore_errors: yes
    - name: copy index.html
      copy: src=index.html dest=/var/www/html/index.html
    - name: start httpd service
      service: name=httpd state=started
