--- # webserver setup
- hosts: appservers
  user: test
  sudo: yes
  vars_prompt:
        - name: pkg
          prompt: Enter package
          private: no
  tasks:
    - name: installing httpd package
      yum: name={{item}} state=installed
      with_items:
           - httpd
           - curl
           - telnet
           - lynx
           - '{{pkg}}'
    - name: copy index.html
      copy: src=index.html dest=/var/www/html/index.html
    - name: start httpd service
      service: name=httpd state=started
