--- # Example of Tomcat Installation 
- hosts: server2
  user: test
  sudo: yes
  gather_facts: yes
  tasks:
   - name: Remove older version of tomcat
     file: path=/usr/local/tomcat state=absent
   - name: Download Tomcat
     get_url: url=http://www.us.apache.org/dist/tomcat/tomcat-8/v8.0.33/bin/apache-tomcat-8.0.33.tar.gz dest=/tmp
   - name: Copy tomcat folder
     command:  mkdir /usr/local/tomcat
   - name: Extract archive
     unarchive: src=/tmp/apache-tomcat-8.0.33.tar.gz /usr/local/tomcat copy=no
   - name: Start Tomcat
     command: nohup  /usr/local/tomcat/apache-tomcat-8.0.33/bin/startup.sh &
