--- # Example of unarchive module
- hosts: server2
  user: test
  become: yes
  gather_facts: yes
  tasks:
   - name: Check whether directory exists
     unarchive: src=playbook.tar.gz dest=/tmp/abc 
